service: lotto-automation
plugins:
  - serverless-offline
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'Dev'}
  region: ${opt:region, 'ap-northeast-2'}

functions:
  main:
    handler: dist/src/main.handler
    environment:
      LOTTO_ID: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/LOTTO_ID}
      LOTTO_PASSWORD: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/LOTTO_PASSWORD}
      DYNAMODB_REGION: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/DYNAMODB_REGION}
      DYNAMODB_ENDPOINT: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/DYNAMODB_ENDPOINT}
      ENCRYPTION_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/ENCRYPTION_KEY}
      ENCRYPTION_ALGORITHM: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/ENCRYPTION_ALGORITHM}
      API_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/API_KEY}
      API_HEADER_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/API_HEADER_KEY}
      HTTP_PORT: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/HTTP_PORT}

    events:
      - http: # root
          method: ANY
          path: /
      - http: # 하위
          method: ANY
          path: '{proxy+}'
