service: lotto-automation
plugins:
  - serverless-offline
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'Dev'}
  region: ${opt:region, 'ap-northeast-2'}
  httpApi:
    id: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/HTTP_API_ID}

functions:
  main:
    handler: dist/src/main.handler
    environment:
      LOTTO_ID: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/LOTTO_ID}
      LOTTO_PASSWORD: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/LOTTO_PASSWORD}
      DYNAMODB_REGION: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/DYNAMODB_REGION}
      DYNAMODB_ENDPOINT: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/DYNAMODB_ENDPOINT}
      ENCRYPTION_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/ENCRYPTION_KEY}
      ENCRYPTION_ALGORITHM: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/ENCRYPTION_ALGORITHM}
      API_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/API_KEY}
      API_HEADER_KEY: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/API_HEADER_KEY}
      HTTP_PORT: ${ssm(ap-northeast-2):/LOTTO_AUTOMATION/HTTP_PORT}

    events:
      - httpApi: # root
          method: ANY
          path: /
      - httpApi: # 하위
          method: ANY
          path: '{proxy+}'
package:
  patterns:
    - 'dist/**'
    - 'node_modules/**'
    - '!src/**' # 소스 파일 제외
    - '!test/**' # 테스트 파일 제외
    - '!*.ts' # TypeScript 파일 제외
    - '!tsconfig*.json' # TypeScript 설정 제외
    - '!jest.config.*' # Jest 설정 제외
    - '!.eslintrc.*' # ESLint 설정 제외
    - '!node_modules/.cache/**'
    - '!node_modules/**/test/**'
    - '!node_modules/**/*.md'
